var projectsArray = [
    {title: 'Guessing Game',
    creation: '2016-07-25',
    image: 'img/guessing-game.png',
    alt: 'screen shot of Guessing Game application',
    description: 'My first coding project.  There are a series of questions asked and a score generated.  It seemed huge at the time.',
    href: 'https://sdcaulley.github.io/guessing-game/'},
    {title: 'Cookie Stand',
    creation: '2016-08-09',
    image: 'img/cookie-stand.png',
    alt: 'screen shot of Cookie Store application',
    description: 'My second coding project.  This was an exercise introducing objects, and object constructors.',
    href: 'https://sdcaulley.github.io/cookie-stand/'},
    {title: 'Bus Mall',
    creation: '2016-09-05',
    image: 'img/bus-mall.png',
    alt: 'screen shot of Bus Mall application',
    description: 'My third coding project.  This added a library - chart.js - and local storage.',
    href: 'https://sdcaulley.github.io/market-analysis-app/'}
];
